export const weeklyWorkoutPlan = [
	{
		key: 1,
		day: 'Monday',
		exercises: [
			{
				id: crypto.randomUUID(),
				name: 'Squats',
				sets: 4,
				reps: 10,
				targetWeight: 80,
				category: 'legs',
				rest: 90,
			},
			{
				id: crypto.randomUUID(),
				name: 'Lunges',
				sets: 3,
				reps: 12,
				targetWeight: 0,
				category: 'legs',
				rest: 60,
			},
			{
				id: crypto.randomUUID(),
				name: 'Leg Press',
				sets: 3,
				reps: 10,
				targetWeight: 120,
				category: 'legs',
				rest: 90,
			},
		],
	},
	{
		key: 2,
		day: 'Tuesday',
		exercises: [
			{
				id: crypto.randomUUID(),
				name: 'Hip Thrusts',
				sets: 4,
				reps: 8,
				targetWeight: 70,
				category: 'glutes',
				rest: 90,
			},
			{
				id: crypto.randomUUID(),
				name: 'Glute Bridge',
				sets: 3,
				reps: 12,
				targetWeight: 0,
				category: 'glutes',
				rest: 60,
			},
			{
				id: crypto.randomUUID(),
				name: 'Cable Kickbacks',
				sets: 3,
				reps: 15,
				targetWeight: 12,
				category: 'glutes',
				rest: 45,
			},
		],
	},
	{
		key: 3,
		day: 'Wednesday',
		exercises: [
			{
				id: crypto.randomUUID(),
				name: 'Plank',
				sets: 3,
				reps: 60,
				targetWeight: null,
				category: 'core',
				rest: 60,
			},
			{
				id: crypto.randomUUID(),
				name: 'Crunches',
				sets: 3,
				reps: 20,
				targetWeight: 0,
				category: 'core',
				rest: 30,
			},
			{
				id: crypto.randomUUID(),
				name: 'Leg Raises',
				sets: 3,
				reps: 15,
				targetWeight: 0,
				category: 'core',
				rest: 30,
			},
		],
	},
	{
		key: 4,
		day: 'Thursday',
		exercises: [
			{
				id: crypto.randomUUID(),
				name: 'Bicep Curls',
				sets: 3,
				reps: 12,
				targetWeight: 12,
				category: 'arms',
				rest: 60,
			},
			{
				id: crypto.randomUUID(),
				name: 'Tricep Dips',
				sets: 3,
				reps: 15,
				targetWeight: 0,
				category: 'arms',
				rest: 60,
			},
			{
				id: crypto.randomUUID(),
				name: 'Hammer Curls',
				sets: 3,
				reps: 10,
				targetWeight: 10,
				category: 'arms',
				rest: 60,
			},
		],
	},
	{
		key: 5,
		day: 'Friday',
		exercises: [
			{
				id: crypto.randomUUID(),
				name: 'Bench Press',
				sets: 4,
				reps: 8,
				targetWeight: 60,
				category: 'chest',
				rest: 90,
			},
			{
				id: crypto.randomUUID(),
				name: 'Incline Dumbbell Press',
				sets: 3,
				reps: 10,
				targetWeight: 20,
				category: 'chest',
				rest: 75,
			},
			{
				id: crypto.randomUUID(),
				name: 'Push-ups',
				sets: 3,
				reps: 20,
				targetWeight: 0,
				category: 'chest',
				rest: 60,
			},
		],
	},
	{
		key: 6,
		day: 'Saturday',
		exercises: [
			{
				id: crypto.randomUUID(),
				name: 'Pull-ups',
				sets: 3,
				reps: 8,
				targetWeight: 0,
				category: 'back',
				rest: 90,
			},
			{
				id: crypto.randomUUID(),
				name: 'Barbell Rows',
				sets: 4,
				reps: 10,
				targetWeight: 50,
				category: 'back',
				rest: 90,
			},
			{
				id: crypto.randomUUID(),
				name: 'Lat Pulldown',
				sets: 3,
				reps: 12,
				targetWeight: 45,
				category: 'back',
				rest: 75,
			},
		],
	},
	{
		key: 7,
		day: 'Sunday',
		exercises: [
			{
				id: crypto.randomUUID(),
				name: 'Stretching Routine',
				sets: 1,
				reps: 15,
				targetWeight: null,
				category: 'stretching',
				rest: 0,
			},
			{
				id: crypto.randomUUID(),
				name: 'Treadmill Walk',
				sets: 1,
				reps: 20,
				targetWeight: null,
				category: 'cardio',
				rest: 0,
			},
			{
				id: crypto.randomUUID(),
				name: 'Foam Rolling',
				sets: 1,
				reps: 10,
				targetWeight: null,
				category: 'stretching',
				rest: 0,
			},
		],
	},
]

export const exerciseCategories = [
	{ id: 1, label: '🦵 Legs', value: 'legs' },
	{ id: 2, label: '🍑 Glutes', value: 'glutes' },
	{ id: 3, label: '🧱 Core / Abs', value: 'core' },
	{ id: 4, label: '💪 Arms', value: 'arms' },
	{ id: 5, label: '🧍 Chest', value: 'chest' },
	{ id: 6, label: '🌀 Back', value: 'back' },
	{ id: 7, label: '🦴 Shoulders', value: 'shoulders' },
	{ id: 8, label: '❤️‍🔥 Full Body', value: 'fullbody' },
	{ id: 9, label: '🧘 Stretching', value: 'stretching' },
	{ id: 10, label: '🏃 Cardio', value: 'cardio' },
	{ id: 11, label: '🛠️ Custom', value: 'custom' },
]

export const weekDays = [
	{ id: 1, name: 'Monday', short: 'Mon' },
	{ id: 2, name: 'Tuesday', short: 'Tue' },
	{ id: 3, name: 'Wednesday', short: 'Wed' },
	{ id: 4, name: 'Thursday', short: 'Thu' },
	{ id: 5, name: 'Friday', short: 'Fri' },
	{ id: 6, name: 'Saturday', short: 'Sat' },
	{ id: 7, name: 'Sunday', short: 'Sun' },
]
